import { Model, ObjectId, Schema, model, models } from "mongoose";

interface AutoGeneratedPlaylistDocument {
  title: string;
  items: ObjectId[];
}

const AutoGeneratedPlaylistSchema = new Schema<AutoGeneratedPlaylistDocument>(
  {
    title: {
      type: String,
      required: true,
    },
    items: [
      {
        type: Schema.Types.ObjectId,
        required: true,
        ref: "Audio",
      },
    ],
  },
  {
    timestamps: true,
  }
);

const AutoGeneratedPlaylist = models.AutoGeneratedPlaylist || model("AutoGeneratedPlaylist", AutoGeneratedPlaylistSchema);

export default AutoGeneratedPlaylist as Model<AutoGeneratedPlaylistDocument>;
